### ISSUE TITLE
Is a new sign build do-able from an API perspective?

### ISSUE THREAD

**Issue by RyokoAsakura** [ColdHeat/nycts-unit#1]
Let us assume I have all of the hardware (I don't, but I could.)

Does the API issue the sign code and if so, could I attach a self-built sign to the API, or does it already have to have an on-board ID?

Thanks for the repos!

**Comment by ColdHeat** [comment]
The API that I've reconstructed can technically be connected to by anything. However I'd prefer if people only put up actual NYCTrainSigns since I'm maintaining the server as a courtesy to actual owners. There are other, superior sources for data if you need one.

**Comment by RyokoAsakura** [comment]
Oh, I understand. If I were to do such a thing, I would use your API server code locally to just do it for me. But, thank you for getting back to the submission so fast!
